services:
  jekyll:
    image: jekyll/jekyll
    command: bash -c "bundle install && jekyll serve --host 0.0.0.0"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll:Z
      - ./vendor/bundle:/usr/local/bundle:Z